language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run
  - vendor/bin/phpspec run --format=dot
