language: php

env:
  global:
    secure: "D6slyX7VQBgSnWRvJoUNVoeR1uXcL+YbiT/W6oh2h6mIY4B2GV1hx9tFss07+4a0IN7XpIK/iGA7vpp3RErCNAVkBLb3ty5FlQ0kzqtg5m8NVPTED5inT/DkKboTpxYbtmIwdcNce34dgTeUuffCQ/ZoMyTzbkUdj6zE/hKeexigpH8TBD4DszrOjqimeC7xlLASureyUKC58FGHdZTehaHFf5bLpfKR+KVXkqpUk+P7RFd8pcLDoLG9yfPdzRb5ZSXmleLpAqZ/QrHUUyIWPxIrL9RjUoC2U4Ev9fNa5v2CWzLJ54AcorMPTWNnAiNYenqremv6pVgh8U6K4FLkYk35bohNWR9kYeO7l7eXwHIw9NC1pvVL2vSVMysjBYj2sgbJw4U4F7QykUzSK4+bZuluDyrrTgWmSyAVEyxDB/BO1QTYSNvKEzO5g03ST9wlsIQHhkR3YMT2xpetm/dzIJVWwARvGrykZOeIRr2xkVPcW84XYbmMF/rXRo9+ROrkd2niaKd3STzOT0Ftu8K4afzoo8WkH7uv/C4nIj2mYSzsTWVDXc6ruKSB+NL5oopNZzmKAmARK+4aINgKrfYtLEHgtVYfiawZqDpSve+vD7F9Rrp7e8afc/TSDOA+Mxpo/FAfeB3f2v4yI2Pd11Ffea/mzFg+f1pk24Y55TM+MT4="

matrix:
  include:
    - php: 5.5
    - php: 5.5
      env: COLLECT_COVERAGE=true

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run
  - vendor/bin/phpspec run --format=dot

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$COLLECT_COVERAGE" == "true" ]]; then bin/report-coverage; fi
