language: php

sudo: false

env:
  global:
    - secure: "Sqw3ZdgVzSxFPpag9Afe/EkQWr0cHp2mFc3Ki8jCCOP/8EB6e5QK0KEX7S3Qsz19K5wPDtgaDGAP9dewEYU1KlVTbgtrl+taBs2qj3n1teINMRMpa6fowJud9iaemrgbzAFiZj8s5/H+yeZSs5t6lbqXw3YHDjOFs6QZTe17axT7HvCtPttTOoqmpBF/yRTEY9fvyQQdWGYwMfC5CLpZwhk6GmwUUTmX11m8ILD3hPI5ItjDlwKjAG5hNB0FePMVRCKCT3IjTtB8Dshc0R+NFDCCqv98DjbKS5i9NMbkwto+IyeVbTHcEqTosIFmFgqJJMw+owmk8SLHw3OYE1sG3oNROwakzpu4l0dnsQYePMqFh1chkK+gEirX9WTv2uBrFmFIKdsKp8xX/AsvC2Y3omFJXIaZUe+Ny5gkURGqPdr/oHU9/J3zmrZ4QeXMRBb+vqw2nTvp44dS4HzPCjQdtts68rEmL0BPC0JRQTGXXWg6/3Tay/2etWzg62eaeUYQYTHahqXVvuN/o7uIcGpVdGi+pVzzc7lxlCTIK9/LiG0tvjbwiTSMXWjfe3n5r4NaHwRBiObNBZN/9g8pwP9hxBFm3bjHjmNYhkPLguepuJtdb4uS4daKnlGaJmx+OO3nP+y82NGhebmWR3+zbs362CkPWjyj3qnEX7YPeBAF6fw="
    - secure: "D6slyX7VQBgSnWRvJoUNVoeR1uXcL+YbiT/W6oh2h6mIY4B2GV1hx9tFss07+4a0IN7XpIK/iGA7vpp3RErCNAVkBLb3ty5FlQ0kzqtg5m8NVPTED5inT/DkKboTpxYbtmIwdcNce34dgTeUuffCQ/ZoMyTzbkUdj6zE/hKeexigpH8TBD4DszrOjqimeC7xlLASureyUKC58FGHdZTehaHFf5bLpfKR+KVXkqpUk+P7RFd8pcLDoLG9yfPdzRb5ZSXmleLpAqZ/QrHUUyIWPxIrL9RjUoC2U4Ev9fNa5v2CWzLJ54AcorMPTWNnAiNYenqremv6pVgh8U6K4FLkYk35bohNWR9kYeO7l7eXwHIw9NC1pvVL2vSVMysjBYj2sgbJw4U4F7QykUzSK4+bZuluDyrrTgWmSyAVEyxDB/BO1QTYSNvKEzO5g03ST9wlsIQHhkR3YMT2xpetm/dzIJVWwARvGrykZOeIRr2xkVPcW84XYbmMF/rXRo9+ROrkd2niaKd3STzOT0Ftu8K4afzoo8WkH7uv/C4nIj2mYSzsTWVDXc6ruKSB+NL5oopNZzmKAmARK+4aINgKrfYtLEHgtVYfiawZqDpSve+vD7F9Rrp7e8afc/TSDOA+Mxpo/FAfeB3f2v4yI2Pd11Ffea/mzFg+f1pk24Y55TM+MT4="

matrix:
  include:
    - php: 5.6
      env: WITH_LOWEST=true
    - php: 5.6
      env: WITH_HIGHEST=true WITH_CS=true WITH_COVERAGE=true
    - php: 7.0
      env: WITH_LOWEST=true
    - php: 7.0
      env: WITH_HIGHEST=true
    - php: 7.1
      env: WITH_LOWEST=true
    - php: 7.1
      env: WITH_HIGHEST=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - source .travis/xdebug.sh
  - xdebug-disable
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest; else composer install; fi

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - mkdir -p build/logs

script:
  - vendor/bin/phpspec run --format=dot --config=phpspec.yml
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

notifications:
  email: false
