language: php

env:
  global:
    secure: "fHd/ClL42Xo81/x3nb1gwBcGoQ9/tiyubrbK9O1bGnlaFGPNpQCIT3qqIvJSzF6VTO8Wc/P8fAQbDJ7i6YYRtginf7ZWXX4DyZleGPueKGuanYuCEIedfy0kjP29l+5fTOvHcJDRCOXVxb8ayg2BhjSIkNNrmIvAeVqCNn0FzWfBmbOtYb7MFUZu3Kw0lfIOnxQKnSSqiearWxWzqKlzAV+TM/G7aJDDRplGzClVTgpA5CLf0hUqnhp5pcOkRNTuIiQluSqM8pNhslVhzmJ1HhEkIujdZJ3gLrUhLsbwhHuEMnYrcGG8HBLaWw4n6KxdaJGR6up4M8inh5BfYgWv1pBqw2ODyOxREnfG9rVKklPDKEjWtTjyeAN28iwHkdQzdQ38EzJ6/4OQ3L2lwdqkSPHnH18itwN3RbPAHv5hila3b5nK8pUryW1hz6AGYeYZRADIsVERBGljMCfO1sfgqEUyVOgQIKONZwPWuUD8rMmg2yAFiMx3w2aK4DTPtvZcN1ZVq+pR6R8DTQlOueiGFQfidfQP5XbXHO9Sgn+Vt2msnaPJPSCeEccoQollmwqrwDtz6teFt6LM4MhhjftOhjyCZmQA8jJTLhgjfAQEHyF3uNQBmSAS2XQkwGGueXwaPv1Y5XXulqSCiUGNM3R9cvSBTQunhiE2PHvlMkNC85w="

matrix:
  include:
    - php: 5.5
    - php: 5.5
      env: COLLECT_COVERAGE=true

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run
  - vendor/bin/phpspec run --format=dot

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$COLLECT_COVERAGE" == "true" ]]; then bin/report-coverage; fi
